### ISSUE TITLE
Easier way to experiment with this gem

### ISSUE THREAD

**Issue by eregon** [kddnewton/parser-prism#8]
I just want to document what I used to not need Bundler as that makes it rather impratical:
```
git clone this-repo
cd parser-prism
gem build parser-prism.gemspec    
gem install parser-prism-*.gem

cd wherever
Change TargetRubyVersion in .rubocop.yml
time rubocop -rparser/prism/rubocop --cache=false FILES
```

It'd be great to add this to the README, unfortunately I don't have time for that right now.

**Comment by kddnewton** [comment]
This should be eased now that it's published to rubygems
