### ISSUE TITLE
String and Xstring literal with multiple lines returns incompatible result

### ISSUE THREAD

**Issue by takaram** [kddnewton/parser-prism#9]
Hi, I am experimenting to apply parser-prism to [Opal](https://github.com/opal/opal).
During the experiment, I noticed some strings are parsed differently than parser gem.

Given this script:
```rb
"foo
bar"

%x{
  date
}
```

Parse result by whitequark/parser:
```
(begin
  (dstr
    (str "foo\n")
    (str "bar"))
  (xstr
    (str "\n")
    (str "  date\n")))
```

Parse result by parser-prism
```
(begin
  (str "foo\nbar")
  (xstr
    (str "\n  date\n")))
```

**Comment by kddnewton** [comment]
Ahh interesting - I didn't know the parser gem split that up. Interestingly that hasn't come up in any of my fixtures so far. I'll have to add it. Thanks for the report!

**Comment by kddnewton** [comment]
@takaram I've moved this issue over to prism itself (https://github.com/ruby/prism/issues/2480), so I'm going to close this one.
